### PR TITLE
[Fix] Getting error `cannot convert 2021-04-23T11:33:12.8437526Z to a time.Time` in azure_storage_account. Closes #100

### LINKED ISSUE #100: Getting an error `cannot convert 2021-04-23T11:33:12.8437526Z to a time.Time` in `azure_storage_account` table
**Describe the bug**
Got the below error

```
select * from azure_storage_account
Error: interfaceToColumnValue failed for column 'encryption_key_vault_properties_last_rotation_time': cannot convert 2021-04-23T11:33:12.8437526Z to a time.Time
```

**Steampipe version (`steampipe -v`)**
: v0.4.1

**Plugin version (`steampipe plugin list`)**
: v0.5.0

**To reproduce**
encrypt the storage account with a customer managed key and Just run the above query.

**Additional context**

### PR DESCRIPTION
**Pull request by rajeshbal65**
…e.Time in table azure_storage_account table. Closes #100

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Add passing integration test logs here
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
select name, encryption_key_vault_properties_last_rotation_time from azure_storage_account;

+---------+----------------------------------------------------+
| name    | encryption_key_vault_properties_last_rotation_time |
+---------+----------------------------------------------------+
| test007 | 2021-04-23 12:10:50                                |
+---------+----------------------------------------------------+
```
</details>

### CODE REVIEW

File: azure/table_azure_storage_account.go [hunk 1]
```diff
@@ -191,7 +191,7 @@ func tableAzureStorageAccount(_ context.Context) *plugin.Table {
 				Name:        "encryption_key_vault_properties_last_rotation_time",
 				Description: "Timestamp of last rotation of the Key Vault Key.",
 				Type:        proto.ColumnType_TIMESTAMP,
-				Transform:   transform.FromField("Account.AccountProperties.Encryption.KeyVaultProperties.LastKeyRotationTimestamp"),
+				Transform:   transform.FromField("Account.AccountProperties.Encryption.KeyVaultProperties.LastKeyRotationTimestamp").Transform(convertDateToTime),
```
Comment (LalitTurbot) [inline azure/table_azure_storage_account.go:194]: @rajeshbal65 
Have you tested it for the case when `LastKeyRotationTimestamp` is null

**Review by cbruno10 — APPROVED** [review]

**Review by LalitTurbot — APPROVED** [review]
LGTM
