### PR TITLE
[Fix] subscription_id column not displaying wrong value in azure_diagnostic_setting table. Closes #98

### LINKED ISSUE #98: subscription_id column might displaying wrong value in `azure_diagnostic_setting` table.
**Describe the bug**

subscription_id column should display `id` the subscription instead of displaying a value as `providers`

```
select name,type,subscription_id from azure_diagnostic_setting;
+------------+---------------------------------------+-----------------+
| name       | type                                  | subscription_id |
+------------+---------------------------------------+-----------------+
| test-diagn | Microsoft.Insights/diagnosticSettings | providers       |
+------------+---------------------------------------+-----------------+

```

**Steampipe version (`steampipe -v`)**
: v0.4.0

**Plugin version (`steampipe plugin list`)**
azure: v0.5.0

**To reproduce**
Run the above query and see the ouput.

**Expected behavior**
It should display  subscription id

**Additional context**

### PR DESCRIPTION
**Pull request by rajeshbal65**
# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Add passing integration test logs here
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
select resource_group, subscription_id from azure_diagnostic_setting;

+----------------+--------------------------------------+
| resource_group | subscription_id                      |
+----------------+--------------------------------------+
| turbot_rg      | d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8 |
| turbot_rg      | d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8 |
| turbot_rg      | d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8 |
+----------------+--------------------------------------+

select resource_group, subscription_id from azure_diagnostic_setting;

+----------------+--------------------------------------+
| resource_group | subscription_id                      |
+----------------+--------------------------------------+
| turbot_rg      | d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8 |
| turbot_rg      | d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8 |
| turbot_rg      | d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8 |
+----------------+--------------------------------------+
```
</details>

### CODE REVIEW

**Comment by rajeshbal65** [comment]
Screenshot 2021-04-23 at 1 43 36 PM

**Review by LalitTurbot — APPROVED** [review]
LGTM

File: azure/table_azure_diagnostic_setting.go [hunk 1]
```diff
@@ -170,3 +173,32 @@ func getDiagnosticSetting(ctx context.Context, d *plugin.QueryData, h *plugin.Hy
...
+	} else if event_hub_authorization_rule_id != nil {
+		resourseGroupID = strings.Split(*event_hub_authorization_rule_id, "/")[4]
+	} else {
+		resourseGroupID = strings.Split(*workspace_id, "/")[4]
+	}
+
+	plugin.Logger(ctx).Trace("resourseGroupID", resourseGroupID)
+
+	return resourseGroupID, nil
+}
```
Comment (LalitTurbot) [inline azure/table_azure_diagnostic_setting.go:204]: why is this a hydrate function when we are not making any API call in here?
Please convert it to a transform function

**Review by LalitTurbot — CHANGES_REQUESTED** [review]
@rajeshbal65 left comment on it

**Review by LalitTurbot — APPROVED** [review]
LGTM
