### PR TITLE
Fixed missing web_application_firewall_configuration details in table azure_application_gateway Closes #765

### LINKED ISSUE #765: Missing `web_application_firewall_configuration details` in Steampipe Azure plugin
**Description**:
I am experiencing an issue with the Steampipe Azure plugin where the web_application_firewall_configuration details are not being populated as expected when querying the azure_application_gateway table. Specifically, the `firewallMode` field which is needed for query development, along with other relevant configuration details, is missing.

**Steps to Reproduce**:

Create an Azure Application Gateway with a WAF policy using the Azure CLI or Azure Portal.
Verify the creation of the WAF policy using az network application-gateway waf-policy list:
```sh
az network application-gateway waf-policy list
[
  {
    "applicationGateways": [
      {
        "id": "/subscriptions/d46........................./resourceGroups/demo/providers/Microsoft.Network/applicationGateways/test-pri",
        "resourceGroup": "demo"
      }
    ],
    "customRules": [],
    "etag": "W/\"8e.................................\"",
    "id": "/subscriptions/d46........................./resourceGroups/demo/providers/Microsoft.Network/ApplicationGatewayWebApplicationFirewallPolicies/test-2",
    "location": "westus2",
    "managedRules": {
      "exclusions": [],
      "managedRuleSets": [
        {
          "ruleGroupOverrides": [],
          "ruleSetType": "OWASP",
          "ruleSetVersion": "3.2"
        }
      ]
    },
    "name": "test-2",
    "policySettings": {
      "fileUploadEnforcement": true,
      "fileUploadLimitInMb": 100,
      "maxRequestBodySizeInKb": 128,
      "mode": "Detection",
      "requestBodyCheck": true,
      "requestBodyEnforcement": true,
      "requestBodyInspectLimitInKB": 128,
      "state": "Enabled"
    },
    "provisioningState": "Succeeded",
    "resourceGroup": "demo",
    "tags": {},
    "type": "Microsoft.Network/ApplicationGatewayWebApplicationFirewallPolicies"
  }
]
```
Attempt to query the web_application_firewall_configuration details using Steampipe:
```sql
select web_application_firewall_configuration from azure_application_gateway;
```
**Expected Behavior**:
The `web_application_firewall_configuration` field should contain the WAF configuration details, including the `firewallMode`.

**Actual Behavior**:
The query returns null for the web_application_firewall_configuration field:

```json
{
 "rows": [
  {
   "web_application_firewall_configuration": null
  }
 ],
 "metadata": null
}
```
**Additional Information**:

- Azure CLI output confirms the existence and configuration of the WAF policy.
- The issue may be related to how the Steampipe Azure plugin retrieves and displays WAF policy details.

### PR DESCRIPTION
**Pull request by ParthaI**
# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Add passing integration test logs here
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
> select name, jsonb_pretty(web_application_firewall_configuration) from azure_application_gateway;
+----------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
| name     | jsonb_pretty                                                                                                                                             |
+----------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
| test2223 | <null>                                                                                                                                                   |
| testgw3  | {                                                                                                                                                        |
|          |     "CustomRules": [                                                                                                                                     |
|          |     ],                                                                                                                                                   |
|          |     "ManagedRules": {                                                                                                                                    |
|          |         "exclusions": [                                                                                                                                  |
|          |         ],                                                                                                                                               |
|          |         "managedRuleSets": [                                                                                                                             |
|          |             {                                                                                                                                            |
|          |                 "ruleSetType": "OWASP",                                                                                                                  |
|          |                 "ruleSetVersion": "3.2",                                                                                                                 |
|          |                 "ruleGroupOverrides": [                                                                                                                  |
|          |                 ]                                                                                                                                        |
|          |             }                                                                                                                                            |
|          |         ]                                                                                                                                                |
|          |     },                                                                                                                                                   |
|          |     "HTTPListeners": null,                                                                                                                               |
|          |     "ResourceState": null,                                                                                                                               |
|          |     "PathBasedRules": null,                                                                                                                              |
|          |     "PolicySettings": {                                                                                                                                  |
|          |         "mode": "Detection",                                                                                                                             |
|          |         "state": "Disabled",                                                                                                                             |
|          |         "requestBodyCheck": true,                                                                                                                        |
|          |         "fileUploadLimitInMb": 100,                                                                                                                      |
|          |         "maxRequestBodySizeInKb": 128                                                                                                                    |
|          |     },                                                                                                                                                   |
|          |     "ProvisioningState": "Succeeded",                                                                                                                    |
|          |     "ApplicationGateways": [                                                                                                                             |
|          |         {                                                                                                                                                |
|          |             "id": "/subscriptions/************************************/resourceGroups/turbot_rg/providers/Microsoft.Network/applicationGateways/testgw3" |
|          |         }                                                                                                                                                |
|          |     ]                                                                                                                                                    |
|          | }                                                                                                                                                        |
+----------+----------------------------------------------------------------------------------------------------------------------------------------------------------+

```
</details>

### CODE REVIEW

File: azure/table_azure_application_gateway.go [hunk 1]
```diff
@@ -405,6 +412,36 @@ func listApplicationGatewayDiagnosticSettings(ctx context.Context, d *plugin.Que
...
 
+func getWebApplicationFirewallConfiguration(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
+	firewallPolicy := h.Item.(network.ApplicationGateway).FirewallPolicy
+
+	// Check for any WAF policy association
+	if firewallPolicy == nil {
+		return nil, nil
+	}
+	policyId := firewallPolicy.ID
+	rgName := strings.Split(*policyId, "/")[4]
```
Comment (misraved) [inline azure/table_azure_application_gateway.go]:
```suggestion
	resourceGroup := strings.Split(*policyId, "/")[4]
```

File: azure/table_azure_application_gateway.go [hunk 2]
```diff
@@ -405,6 +412,36 @@ func listApplicationGatewayDiagnosticSettings(ctx context.Context, d *plugin.Que
...
+	session, err := GetNewSession(ctx, d, "MANAGEMENT")
+	if err != nil {
+		return nil, err
+	}
+	subscriptionID := session.SubscriptionID
+
+	client := network.NewWebApplicationFirewallPoliciesClientWithBaseURI(session.ResourceManagerEndpoint, subscriptionID)
+	client.Authorizer = session.Authorizer
+
+	op, err := client.Get(ctx, rgName, policyname)
```
Comment (misraved) [inline azure/table_azure_application_gateway.go]:
```suggestion
	op, err := client.Get(ctx, resourceGroup, policyname)
```

**Review by misraved — COMMENTED** [review]
@ParthaI could you please take a look at the review comments? Thanks !!

**Review by misraved — APPROVED** [review]
