### PR TITLE
Fix column network_access_policy in table azure_compute_disk closes #446

### LINKED ISSUE #446: Fix column network_access_policy in table azure_compute_disk
**Describe the bug**
We are getting null value for column `network_access_policy` in table azure_compute_disk

**Steampipe version (`steampipe -v`)**
 0.13.1-rc.1

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by ParthaI**
# Integration test logs
<details>
  <summary>Logs</summary>
  
```
N/A
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
> select name, network_access_policy from azure_compute_disk
+-----------------------------------------------------------+-----------------------+
| name                                                      | network_access_policy |
+-----------------------------------------------------------+-----------------------+
| newwarriors-AAA_OsDisk_1_eac82728fe9a4e58b3db75d0518dd24d | AllowAll              |
+-----------------------------------------------------------+-----------------------+
```
</details>

### CODE REVIEW

File: azure/table_azure_compute_disk.go [hunk 1]
```diff
@@ -309,6 +310,7 @@ func listAzureComputeDisks(ctx context.Context, d *plugin.QueryData, _ *plugin.H
 
 	for _, disk := range result.Values() {
 		d.StreamListItem(ctx, disk)
+		plugin.Logger(ctx).Info("Network Access Policy without page ===>>", disk.NetworkAccessPolicy)
```
Comment (cbruno10) [inline azure/table_azure_compute_disk.go:313]: I think we should take this out? Please do not leave debug statements in

File: azure/table_azure_compute_disk.go [hunk 2]
```diff
@@ -324,6 +326,7 @@ func listAzureComputeDisks(ctx context.Context, d *plugin.QueryData, _ *plugin.H
 
 		for _, disk := range result.Values() {
 			d.StreamListItem(ctx, disk)
+			plugin.Logger(ctx).Info("Network Access Policy with page ===>>", disk.NetworkAccessPolicy)
```
Comment (cbruno10) [inline azure/table_azure_compute_disk.go:329]: Same as above

**Review by cbruno10 — CHANGES_REQUESTED** [review]
@ParthaI Please see comments

**Review by cbruno10 — APPROVED** [review]
