### PR TITLE
Fix GetNewSession function to cache credentials session correctly. Fixes #441

### LINKED ISSUE #441: Fix `GetNewSession` function to cache credentials session correctly
**Describe the bug**
When using the Steampipe in service mod `(i.e. steampipe service start)` and using the default azure CLI method for authentication, the plugin was not caching correctly and making `az account get-access-token` repeatedly.

https://steampipe.slack.com/archives/C01UECB59A7/p1642509951012600

**Steampipe version (`steampipe -v`)**
Example: v0.11.1

**Plugin version (`steampipe plugin list`)**
Example: v0.23.1

**To reproduce**
```
#!/usr/bin/env bash

set -EeuoC pipefail
trap cleanup SIGINT SIGTERM ERR EXIT

cleanup() {
  trap - SIGINT SIGTERM ERR EXIT
}

steampipe service start
STEAMPIPE_LOG=debug
STEAMPIPE_CONNECTION_NAME=azure

declare -a AZURE_TABLES=(
  "azure_storage_account"
  "azure_compute_disk"
  "azure_subscription"
  )

${STEAMPIPE_CONNECTION_NAME} and dump it as JSON, CSV and Table format into ${PWD}. Grab a c[_]..."

# Dispatch required cloud provider
for table in "${AZURE_TABLES[@]}"
do
     echo "[*] Fetching steampipe table ${table}..."
     if [ -f "${PWD}/${STEAMPIPE_CONNECTION_NAME}_${table}.log" ]; then
       echo "[!] WARN: ${PWD}/${STEAMPIPE_CONNECTION_NAME}_${table}.log already exists! Need c[_]? Skipping ${table}..."
     else
       steampipe query "select * from ${STEAMPIPE_CONNECTION_NAME}.${table}" > ${STEAMPIPE_CONNECTION_NAME}_${table}.log
       steampipe query "select * from ${STEAMPIPE_CONNECTION_NAME}.${table}" --output json > ${STEAMPIPE_CONNECTION_NAME}_${table}.json
       steampipe query "select * from ${STEAMPIPE_CONNECTION_NAME}.${table}" --output csv > ${STEAMPIPE_CONNECTION_NAME}_${table}.csv
     fi
done
```

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by LalitTurbot**
# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Add passing integration test logs here
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
Add example SQL query results here (please include the input queries as well)
```
</details>

### CODE REVIEW

File: azure/service.go [hunk 1]
```diff
@@ -165,16 +169,17 @@ func GetNewSession(ctx context.Context, d *plugin.QueryData, tokenAudience strin
...
 			return nil, err
 		}
 
 		adalToken, err := token.ToADALToken()
-		expiresOn = adalToken.Expires()
+		expiresOn = types.Time(adalToken.Expires())
 
 		if err != nil {
-			logger.Debug("GetNewSession__", "NewAuthorizerFromCLIWithResource error", err)
+			logger.Error("GetNewSession__", "Get token from Azure CLI error", err)
```
Comment (cbruno10) [inline azure/service.go:182]: What level do we usually use, Warn or Error, for these types of messages?

File: azure/service.go [hunk 2]
```diff
@@ -203,18 +210,20 @@ func GetNewSession(ctx context.Context, d *plugin.QueryData, tokenAudience strin
...
 		ResourceManagerEndpoint: settings.Environment.ResourceManagerEndpoint,
 		StorageEndpointSuffix:   settings.Environment.StorageEndpointSuffix,
 		SubscriptionID:          subscriptionID,
 		TenantID:                tenantID,
 	}
 
-	if sess.Expires != nil {
+	if expiresOn != nil {
 		d.ConnectionManager.Cache.SetWithTTL(cacheKey, sess, time.Until(*sess.Expires))
+		logger.Info("Session saved in cache with expiry in", "minutes", (time.Until(*sess.Expires)).Minutes())
```
Comment (cbruno10) [inline azure/service.go:223]: Similar to my other questions above, should this line and the one below it be debug level?

**Review by cbruno10 — APPROVED** [review]
