### PR TITLE
[FIX] Azure query for Key Vault runs to infinite loop. Closes #35

### LINKED ISSUE #35: The Azure query for Key Vault runs to infinite loop.
While executing this query, it runs in to loop. There are only 3 no of key-vaults in the subscription. 

```
> select
  name,
  id,
  soft_delete_enabled,
  soft_delete_retention_in_days
from
  azure_key_vault
```
⠏ Loading results: 275 
⠸ Loading results: 553 
⠇ Loading results: 646 
⠋ Loading results: 646 
⠹ Loading results: 646 
⠼ Loading results: 646 
⠦ Loading results: 646 
Error: pq: rpc error: code = Unavailable desc = transport is closing ( This comes after I stopped the service with **steampipe service stop --force**)
**Connected again to execute the same query** 

**abc % **steampipe query****
Welcome to Steampipe v0.2.2
For more information, type .help
> select
  name,
  id,
  soft_delete_enabled,
  soft_delete_retention_in_days
from
  azure_key_vault
⠙ Loading results: 275

### PR DESCRIPTION
**Pull request by Subhajit97**
# Integration test logs
<details>
  <summary>Logs</summary>
  
```
No env file present for the current environment:  staging 
 Falling back to .env config
No env file present for the current environment:  staging
customEnv TURBOT_TEST_EXPECTED_TIMEOUT 300

SETUP: tests/azure_key_vault []

PRETEST: tests/azure_key_vault

TEST: tests/azure_key_vault
Running terraform
data.azurerm_client_config.current: Refreshing state...
data.null_data_source.resource: Refreshing state...
azurerm_resource_group.named_test_resource: Creating...
azurerm_resource_group.named_test_resource: Creation complete after 5s [id=/subscriptions/********-****-****-****-************/resourceGroups/turbottest35668]
azurerm_key_vault.named_test_resource: Creating...
azurerm_key_vault.named_test_resource: Still creating... [10s elapsed]
azurerm_key_vault.named_test_resource: Still creating... [20s elapsed]
azurerm_key_vault.named_test_resource: Still creating... [30s elapsed]
azurerm_key_vault.named_test_resource: Still creating... [40s elapsed]
azurerm_key_vault.named_test_resource: Still creating... [50s elapsed]
azurerm_key_vault.named_test_resource: Still creating... [1m0s elapsed]
azurerm_key_vault.named_test_resource: Still creating... [1m10s elapsed]
azurerm_key_vault.named_test_resource: Still creating... [1m20s elapsed]
azurerm_key_vault.named_test_resource: Still creating... [1m30s elapsed]
azurerm_key_vault.named_test_resource: Still creating... [1m40s elapsed]
azurerm_key_vault.named_test_resource: Still creating... [1m50s elapsed]
azurerm_key_vault.named_test_resource: Still creating... [2m0s elapsed]
azurerm_key_vault.named_test_resource: Still creating... [2m10s elapsed]
azurerm_key_vault.named_test_resource: Still creating... [2m20s elapsed]
azurerm_key_vault.named_test_resource: Still creating... [2m30s elapsed]
azurerm_key_vault.named_test_resource: Creation complete after 2m30s [id=/subscriptions/********-****-****-****-************/resourceGroups/turbottest35668/providers/Microsoft.KeyVault/vaults/turbottest35668]
azurerm_key_vault_access_policy.named_test_resource: Creating...
azurerm_key_vault_access_policy.named_test_resource: Still creating... [10s elapsed]
azurerm_key_vault_access_policy.named_test_resource: Creation complete after 13s [id=/subscriptions/********-****-****-****-************/resourceGroups/turbottest35668/providers/Microsoft.KeyVault/vaults/turbottest35668/objectId/e416149c-435f-47ac-994e-7b87a45652af]

Warning: Deprecated Resource

The null_data_source was historically used to construct intermediate values to
re-use elsewhere in configuration, the same can now be achieved using locals


Apply complete! Resources: 3 added, 0 changed, 0 destroyed.

Outputs:

object_id = e416149c-435f-47ac-994e-7b87a45652af
resource_aka = azure:///subscriptions/********-****-****-****-************/resourceGroups/turbottest35668/providers/Microsoft.KeyVault/vaults/turbottest35668
resource_aka_lower = azure:///subscriptions/********-****-****-****-************/resourcegroups/turbottest35668/providers/microsoft.keyvault/vaults/turbottest35668
resource_id = /subscriptions/********-****-****-****-************/resourceGroups/turbottest35668/providers/Microsoft.KeyVault/vaults/turbottest35668
resource_name = turbottest35668
subscription_id = ********-****-****-****-************
tenant_id = cdffd708-7da0-4cea-abeb-0a4c334d7f64

Running SQL query: test-get-query.sql
[
  {
    "enabled_for_deployment": false,
    "enabled_for_disk_encryption": false,
    "enabled_for_template_deployment": false,
    "id": "/subscriptions/********-****-****-****-************/resourceGroups/turbottest35668/providers/Microsoft.KeyVault/vaults/turbottest35668",
    "name": "turbottest35668",
    "region": "westus",
    "resource_group": "turbottest35668",
    "sku_name": "standard",
    "tenant_id": "cdffd708-7da0-4cea-abeb-0a4c334d7f64",
    "type": "Microsoft.KeyVault/vaults",
    "vault_uri": "https://turbottest35668.vault.azure.net/"
  }
]
✔ PASSED

Running SQL query: test-hydrate-query.sql
[
  {
    "access_policies": [
      {
        "objectId": "e416149c-435f-47ac-994e-7b87a45652af",
        "permissions": {
          "certificates": [],
          "keys": [
            "get"
          ],
          "secrets": [
            "get"
          ],
          "storage": []
        },
        "tenantId": "cdffd708-7da0-4cea-abeb-0a4c334d7f64"
      }
    ],
    "akas": [
      "azure:///subscriptions/********-****-****-****-************/resourceGroups/turbottest35668/providers/Microsoft.KeyVault/vaults/turbottest35668",
      "azure:///subscriptions/********-****-****-****-************/resourcegroups/turbottest35668/providers/microsoft.keyvault/vaults/turbottest35668"
    ],
    "name": "turbottest35668",
    "tags": {
      "name": "turbottest35668"
    },
    "title": "turbottest35668"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql
[
  {
    "id": "/subscriptions/********-****-****-****-************/resourceGroups/turbottest35668/providers/Microsoft.KeyVault/vaults/turbottest35668",
    "name": "turbottest35668"
  }
]
✔ PASSED

Running SQL query: test-not-found-query.sql
null
✔ PASSED

Running SQL query: test-turbot-query.sql
[
  {
    "akas": [
      "azure:///subscriptions/********-****-****-****-************/resourceGroups/turbottest35668/providers/Microsoft.KeyVault/vaults/turbottest35668",
      "azure:///subscriptions/********-****-****-****-************/resourcegroups/turbottest35668/providers/microsoft.keyvault/vaults/turbottest35668"
    ],
    "name": "turbottest35668",
    "tags": {
      "name": "turbottest35668"
    },
    "title": "turbottest35668"
  }
]
✔ PASSED

POSTTEST: tests/azure_key_vault

TEARDOWN: tests/azure_key_vault

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
N/A
```
</details>

### CODE REVIEW

File: azure/table_azure_key_vault.go [hunk 1]
```diff
@@ -170,42 +185,47 @@ func listKeyVaults(ctx context.Context, d *plugin.QueryData, _ *plugin.HydrateDa
...
-		result, err := keyVaultClient.ListBySubscription(ctx, nil)
-		if err != nil {
-			return nil, err
-		}
-
-		for _, vault := range result.Values() {
-			d.StreamListItem(ctx, vault)
-		}
-		result.NextWithContext(context.Background())
-		pagesLeft = result.NotDone()
```
Comment (LalitTurbot) [inline azure/table_azure_key_vault.go:185]: @Subhajit97 can you also raise an issue for the same on Azure SDK mentioning when it happens

**Review by LalitTurbot — APPROVED** [review]

**Review by cbruno10 — APPROVED** [review]
